# Generated by Django 2.2 on 2019-04-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=128, unique=True, verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
        migrations.CreateModel(
            name='ServicesKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_kind', models.CharField(max_length=128, unique=True, verbose_name='Вид услуги')),
                ('service_type', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='main.ServicesTypes', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Вид услуги',
                'verbose_name_plural': 'Виды услуг',
            },
        ),
        migrations.CreateModel(
            name='Applictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('treatment_data', models.DateField(auto_now_add=True, verbose_name='Дата обращения')),
                ('is_close', models.BooleanField(verbose_name='Закрыта ли заявка')),
                ('service_kind', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='main.ServicesKinds', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
